# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-06 13:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('term_start_dt', models.DateField()),
                ('term_end_dt', models.DateField()),
                ('cat_yr', models.IntegerField()),
            ],
        ),
    ]
